### ISSUE TITLE
display README.md

### ISSUE THREAD

**Issue by lin1005q** [alehaa/nginx-fancyindex-flat-theme#11]
Can you directly display the content of the README.md file in the current directory, just like github

**Comment by alehaa** [comment]
That could be possible with JavaScript. However, this project is just a simple theme of nginx's fancyindex module, so we shouldn't put to much new functionality into it. README files mostly appear in git repositories, so I suggest to use a git repository viewer instead, like [GitList](http://gitlist.org) or [Gitea](https://gitea.com).

**Comment by lin1005q** [comment]
Or directly display the txt format.Sometimes there will be some documentation, markdown is better, but txt is also available
