### ISSUE TITLE
theme.css not found

### ISSUE THREAD

**Issue by harryqt** [alehaa/nginx-fancyindex-flat-theme#4]
It works but in the console I have this error.

`GET http://localhost/theme/theme.css net::ERR_ABORTED 404 (Not Found)`

![chrome_2019-07-26_22-08-22](https://user-images.githubusercontent.com/18257605/61967030-f0984180-aff1-11e9-8a65-229ed4e6a4cc.png)

**Comment by alehaa** [comment]
Did you set a location for the `/theme` directory in your nginx configuration?

**Comment by harryqt** [comment]
Yes, I did. I also copied `/layout` directories files to `/theme` directory. Otherwise it was not working.

```
location /theme {
    alias "C:/nginx/theme";
    try_files $uri $uri/ = 404;
}
```

I put this on `http block`.

```
#Fancyindex
fancyindex             on;
fancyindex_header      "/theme/header.html";
fancyindex_footer      "/theme/footer.html";
fancyindex_show_path   off;
fancyindex_name_length 255;
fancyindex_exact_size  off;
fancyindex_localtime   on;
```

By the way, there is no `theme.css` file in this repo. There is `theme.less`

It works, but I do get that error in console.

![2019-07-26_22-22-35](https://user-images.githubusercontent.com/18257605/61967806-f727b880-aff3-11e9-972e-0f88e2f81d72.png)

**Comment by harryqt** [comment]
I have now compiled `.less` to `.css` which fixed the issue..

But TBH without `theme.css` it's looks much better IMO. 😍
