### ISSUE TITLE
Dark version?

### ISSUE THREAD

**Issue by samip5** [alehaa/nginx-fancyindex-flat-theme#5]
Could we get a dark variant of this theme? Thank you. :)

**Comment by alehaa** [comment]
Do you mean a permanent dark version, or one that uses the `refers-color-scheme` CSS media feature to dynamically switch between both?

**Comment by samip5** [comment]
Permament

**Comment by alehaa** [comment]
I've just updated the CSS to honor the `prefers-color-scheme` media query. This allows an easy setup without the need to update the HTML file to use the chosen CSS style.

For a fixed dark-mode, you can update the variables directly in [body.less](https://github.com/alehaa/nginx-fancyindex-flat-theme/blob/master/layout/less/body.less#L29) and [list.less](https://github.com/alehaa/nginx-fancyindex-flat-theme/blob/master/layout/less/list.less#L35) files.
