### ISSUE TITLE
Could not download tar.gz from releses

### ISSUE THREAD

**Issue by khurshid-alam** [alehaa/nginx-fancyindex-flat-theme#6]
When I try to download it simply opens the page in the browser (Chrome/Firefox) and claims it is an xml page !!

**Comment by alehaa** [comment]
This seems to be an issue related to the GitHub backend, as this is an AWS error response. I contacted the GitHub support for help with this issue.

**Comment by alehaa** [comment]
This issue should be fixed now. Details are available at [GitHub Status](https://www.githubstatus.com/incidents/1p369ttzrnqy).
